version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: google-closure-compiler
    versions:
    - 20210202.0.0
    - 20210302.0.0
