sudo: false

language: node_js

env:
  global:
    - CC_TEST_REPORTER_ID=36090871ed7524206012db9d5d5e3a69ecf78c034d50d3d330b6549bc7c03758

node_js:
  - 8
  - 6
  - 4

before_install:
  - npm config set spin false
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1
  - node -v
  - npm -v

before_script:
  - greenkeeper-lockfile-update
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run test-cov

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - npm run clean-cov
  - greenkeeper-lockfile-upload
