git:
  depth: 10
sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - 10
  - 8
  - 6

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
  - export PATH=$HOME/.yarn/bin:$PATH
  - node -v
  - npm -v
  - yarn -v

script:
  - yarn test
  - codecov
