sudo: false

language: node_js

node_js:
  - "0.12"
  - "4"
  - "5"
  - "stable"

before_install:
  - "npm config set spin false"
  - "node -v"
  - "npm -v"

script:
  - "npm run test-cov"

after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
  - "npm run clean-cov"
