init:
  - git config --global core.autocrlf input

environment:
  matrix:
  - nodejs_version: "0.12"
  - nodejs_version: "4"
  - nodejs_version: "5"
  - nodejs_version: "6"

skip_tags: true

platform:
  - x86
  - x64

version: "{build}"

build: off

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - set PATH=%APPDATA%\npm;%PATH%
  - node --version
  - npm --version
  - npm install

test_script:
  - cmd: npm run test
