init:
  - git config --global core.autocrlf input

environment:
  matrix:
  - nodejs_version: "0.12"
  - nodejs_version: "1"
  - nodejs_version: "2"
  - nodejs_version: "3"
  - nodejs_version: "4"
  - nodejs_version: "5"

skip_tags: true

platform:
  - x86
  - x64

version: "{build}"

build: off

cache:
  - '%AppData%\npm-cache'

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - set PATH=%APPDATA%\npm;%PATH%
  - node --version
  - npm --version
  - npm install grunt-cli -g
  - npm install

test_script:
  - cmd: grunt test --no-color
